name: Typecheck

# Conditions de déclenchement de l'action
on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  typecheck:
    runs-on: ubuntu-latest
    name: Check type
    steps:
    - uses: actions/checkout@v3
    # Commandes à lancer lors de l'action
    - run: npm install
    - run: npx nuxi typecheck